In [18]:
import numpy as np

def p(x, coeff):
    a0 = coeff[0]
    n = len(coeff)-1
    p = a0 + coeff[1:]@np.cumprod(np.ones(n)*x) 
    return p

In [21]:
p(1/2, [2,4,2])

4.5

In [20]:
2 + 4*(0.5) + 2*(.5)**2

4.5

In [208]:
class Poly:
  """
  Evaluates and differentiates polynomials
  p(x) = a_0 x^0 + ... + a_N x^N,

  """
  def __init__(self, coeff):
    """
    Initialize with state x0 and parameter r
    """
    self.coeff = np.asarray(coeff)
    self.N = len(self.coeff)-1
    self.exp = np.asarray(range(self.N+1))

  def __call__(self, x):
    "Evaluate the polynomial at x"
    a0 = self.coeff[0]
    p = a0 + self.coeff[1:]@np.cumprod(np.ones(self.N)*x) 
    return p
    
  def diff(self):
    "Differentiate the polynomial"   
    new_coeff = (self.exp*self.coeff)[1:]
    self.coeff = new_coeff
    self.N = len(new_coeff)-1
    self.exp = np.asarray(range(self.N+1))
    return new_coeff

In [209]:
P1 = Poly([1,2,4,2])
P2 = Poly([1,2,3])

In [210]:
P1.exp

array([0, 1, 2, 3])

In [211]:
P1.coeff

array([1, 2, 4, 2])

In [212]:
P1.N

3

In [213]:
P1.diff()

array([2, 8, 6])

In [214]:
P1.coeff

array([2, 8, 6])

In [215]:
P1.N

2

In [216]:
P1.exp

array([0, 1, 2])

In [217]:
P3 = P2.diff()

In [218]:
P3

array([2, 6])