In [46]:
import numpy as np
q = [.25,.50,.25]
from random import uniform
def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]

In [49]:
sample(q)

2

In [50]:
a = np.random.random_sample(5)
np.cumsum(q)

array([ 0.25,  0.75,  1.  ])

In [26]:
np.searchsorted(q,a)

array([2, 2, 1, 0, 0], dtype=int64)

In [67]:
class discreteRV:
    
    def __init__(self,q):
        self.distro = q
        self.cdf = np.cumsum(q)
        
    def draw(self,n):
        a = np.random.random_sample(n)
        d = np.searchsorted(self.cdf,a)
        return(d)

In [79]:
distro_1 = discreteRV([0.25,.50,.25])
distro_1.cdf

array([ 0.25,  0.75,  1.  ])

In [88]:
distro_1.draw(5)

array([1, 1, 2, 2, 2], dtype=int64)