In [1]:
import numpy as np

x = np.random.uniform(0, 1, size=1000000)
x.mean()

0.5003062144903752

In [2]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [3]:
type(a)

numpy.ndarray

In [4]:
z = np.empty(3)
z

array([0., 0., 0.])

In [5]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[2., 2.],
       [2., 2.]])

In [6]:
A = np.array((1, 2))
B = np.array((10, 20))
A @ B

50

In [15]:
coeff = np.array([2, 4, 4, 2])
n = coeff.size
x = 3
z = np.ones(5)*x

z
n

4

In [17]:
z.cumprod()

array([  3.,   9.,  27.,  81., 243.])

In [21]:
def p (coeff, x):
    n = len(coeff)
    z = np.ones(n)*x
    z[0] = 1
    return np.cumprod(z)@coeff

In [22]:
coef = np.ones(3)
print(coef)
print(p(coef,1))
# For comparison
q = np.poly1d(coef)
print(q(1))

[1. 1. 1.]
3.0
3.0
